[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
    "setuptools_scm>=3.3.1",
    "pooch>=1.6.0",
]

[tool.black]
line-length = 140
target-version = ['py37']
skip-string-normalization = true
